services:
    form.type.autovalidator:
        class: Citra\Mootools\AutoValidatorBundle\Form\Type\AutoValidatorType
        arguments:
            - "@service_container"
        tags:
            - { name: form.type, alias: autovalidator }
