# CRUD Routing Configuration
options:
    class:     IluniBookBundle:CRUD\Community
    name:      community

# community_show:
#     pattern:  /{id}/show
#     defaults: { _controller: "IluniBookBundle:CRUD\Community:show" }
#     requirements: { id:  \d+ }
#
# community_new:
#     pattern:  /new
#     defaults: { _controller: "IluniBookBundle:CRUD\Community:new" }
#
# community_create:
#     pattern:  /create
#     defaults: { _controller: "IluniBookBundle:CRUD\Community:create" }
#     requirements: { _method: post }
#
# community_edit:
#     pattern:  /{id}/edit
#     defaults: { _controller: "IluniBookBundle:CRUD\Community:edit" }
#     requirements: { id:  \d+ }
#
# community_update:
#     pattern:  /{id}/update
#     defaults: { _controller: "IluniBookBundle:CRUD\Community:update" }
#     requirements: { _method: post }
#
# community_delete:
#     pattern:  /{id}/delete
#     defaults: { _controller: "IluniBookBundle:CRUD\Community:delete" }
#     requirements: { _method: post }
#

