org_show:
    pattern:  /{id}/show
    defaults: { _controller: "IluniBookBundle:CRUD\Organization:show" }
    requirements: { id:  \d+ }

org_new:
    pattern:  /new
    defaults: { _controller: "IluniBookBundle:CRUD\Organization:new" }

org_create:
    pattern:  /create
    defaults: { _controller: "IluniBookBundle:CRUD\Organization:create" }
    requirements: { _method: post }

org_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "IluniBookBundle:CRUD\Organization:edit" }
    requirements: { id:  \d+ }

org_update:
    pattern:  /{id}/update
    defaults: { _controller: "IluniBookBundle:CRUD\Organization:update" }
    requirements: { _method: post }

org_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "IluniBookBundle:CRUD\Organization:delete" }
    requirements: { _method: post }

# utility for testing purpose, master-detail crawler
org_first:
    pattern:  /first.{_format}
    defaults: { _controller: "IluniBookBundle:CRUD\Organization:first", _format: html }
    requirements: { _format: (html|json), _method: GET }
