Iluni\BookBundle\Entity\Detail\AlumniContacts:
  type: entity
  repositoryClass: Iluni\BookBundle\Repository\Detail\AlumniContactsRepository
  table: null
  manyToOne:
    alumni:
      targetEntity: Iluni\BookBundle\Entity\Alumni
      joinColumns:
        aid:
          referencedColumnName: aid
      orphanRemoval: false
  lifecycleCallbacks: {  }
