parameters:
    locale: id

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine.yml }
    - { resource: sonata.yml }
    - { resource: "@OricloneBundle/Resources/config/config.yml" }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    translator: { fallback: en }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale: %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

    form:
        resources:
            - 'IluniBookBundle:Shared/Form:forms_override.html.twig'
            - 'LookupModalBundle:Form:lookupmodal_widget.html.twig'
            - 'DatePickerBundle:Form:datepicker_widget.html.twig'


# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
#    read_from: %kernel.root_dir%/../web/bundles/oriclonetheme
#    write_to:  %kernel.root_dir%/../web
    bundles:
        - MootoolsBundle
        - OricloneBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar



# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

oriclone:
    # debug_css: true
    # effects:   false

    layout:
        sitename:    AlumniBook
        logo:        logo-orikara

        classes:
            background_header: yellow
            # just black, no gradient
            variation_top:     ""

