imports:
    - { resource: services.form.yml }
    - { resource: services.sonata.yml }

services:
#    iluni_book.example:
#        class: %iluni_book.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    # twig
    iluni_book.twig.extension:
        class: Iluni\BookBundle\Library\Twig\BookExtension
        tags:
            - { name: twig.extension }
        arguments: [ @service_container ]

    iluni_book.twig.tab:
        class: Iluni\BookBundle\Library\Twig\BookTabExtension
        tags:
            - { name: twig.extension }
        arguments: [ @router ]

    # summary (total) repository
    iluni_book.repository.summary:
        class: Iluni\BookBundle\Repository\SummaryRepository
        arguments:
            entity_manager: "@doctrine.orm.entity_manager"

    # options Holder, processing parameter related
    iluni_book.filter_options_holder:
        class: Iluni\BookBundle\Library\OptionsHolder\FilterOptionsHolder
        arguments: [ @session ]


