# src/Iluni/BookBundle/Resources/config/validation.yml
Iluni\BookBundle\Entity\Alumni:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
                max: 50
        gender:
            - Choice: { choices: [M, F] }
        birthdate:
            - Date: ~


Iluni\BookBundle\Entity\Organization:
    constraints:
        - Callback:
            methods:   [isParentValid]
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
                max: 50

Iluni\BookBundle\Entity\Community:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
                max: 50
        typeId:
            - Choice: { choices: [1, 2] }

Iluni\BookBundle\Entity\Detail\AlumniCommunities:
    properties:
        classYear:
            - NotBlank: ~
            - Range:
                min: 1960
                max: 2020
            - Type:
                type: integer

Iluni\BookBundle\Entity\Base\Address:
    constraints:
        - Callback:
            methods:   [isCombinationValid]

Iluni\BookBundle\Entity\Base\Contacts:
    properties:
        contact:
            - NotBlank: ~
            - Length:
                min: 3
        contactType:
            - NotBlank: ~

Iluni\BookBundle\Entity\Detail\AlumniExperiences:
    properties:
        organization:
            - NotBlank: ~
            - Length:
                min: 3
        yearIn:
            - Range:
                min: 1960
                max: 2020
            - Type:
                type: integer
        yearOut:
            - Range:
                min: 1960
                max: 2020
            - Type:
                type: integer

Iluni\BookBundle\Entity\Detail\AlumniDegrees:
    properties:
        institution:
            - NotBlank: ~
            - Length:
                min: 3
        admitted:
            - Range:
                min: 1960
                max: 2020
            - Type:
                type: integer
        graduated:
            - Range:
                min: 1960
                max: 2020
            - Type:
                type: integer

Iluni\BookBundle\Entity\Detail\AlumniCertifications:
    properties:
        certification:
            - NotBlank: ~
            - Length:
                min: 5
                max: 50
        institution:
            - Length:
                min: 5
                max: 20


# Below is used by Sonata

Iluni\BookBundle\Entity\Category\Religion:
    constraints:
        - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: id

Iluni\BookBundle\Entity\Category\Competency:
    constraints:
        - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: id

Iluni\BookBundle\Entity\Category\BizField:
    constraints:
        - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: id

Iluni\BookBundle\Entity\Category\JobType:
    constraints:
        - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: id

Iluni\BookBundle\Entity\Category\JobPosition:
    constraints:
        - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: id

Iluni\BookBundle\Entity\Category\Strata:
    constraints:
        - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: id

Iluni\BookBundle\Entity\Category\Program:
    constraints:
        - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: id

Iluni\BookBundle\Entity\Category\Faculty:
    constraints:
        - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: id

Iluni\BookBundle\Entity\Category\Department:
    constraints:
        - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: id

Iluni\BookBundle\Entity\Category\ContactType:
    constraints:
        - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: id

Iluni\BookBundle\Entity\Category\Country:
    constraints:
        - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: id

Iluni\BookBundle\Entity\Category\Province:
    constraints:
        - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: id

Iluni\BookBundle\Entity\Category\District:
    constraints:
        - \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: id
