<?php

namespace Iluni\BookBundle\Repository\Detail;

use Iluni\BookBundle\Repository\CommonConstraintRepository;

/**
 * ACertificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlumniCertificationsRepository extends CommonConstraintRepository
{
    protected static $order_by_choices = array(
        1  => 'r.id',
        21 => 'a.name',
        41 => 'r.certification',
        42 => 'r.institution',
        101 => 'ac.community, a.name',
        102 => 'ac.department, ac.program, ac.classYear, a.name',
        103 => 'ac.faculty, ac.department, ac.program, ac.classYear, a.name',
        104 => 'ac.program, ac.department, ac.classYear, a.name',
        105 => 'ac.classYear, ac.department, a.name'    // default
    );

    public function findQueryFilter($constraint = array())
    {
        $this->qb = $this->createQueryBuilder('r')
            ->select('r, a, ac')
            ->leftJoin('r.alumni', 'a')
            ->leftJoin('a.acommunities', 'ac');

        $this->checkConstraintOrderBy($constraint);
        $this->checkConstraintCommunity($constraint);

        return $this->qb->getQuery();
    }
}

