<?php

namespace Iluni\BookBundle\Repository\Detail;

use Iluni\BookBundle\Repository\CommonConstraintRepository;

/**
 * MContactsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapContactsRepository extends CommonConstraintRepository
{
    protected static $order_by_choices = array(
        6  => 'r.id',
        26 => 'a.name',
        27 => 'o.name',
        47 => 'ct.id'
    );

    public function findQueryFilter($constraint = array())
    {
        $this->qb = $this->createQueryBuilder('r')
            ->select('r, m, a, o, ac, ct')
            ->leftJoin('r.alumni_org_map', 'm')
            ->leftJoin('m.alumni', 'a')
            ->leftJoin('a.acommunities', 'ac')
            ->leftJoin('m.organization', 'o')
            ->leftJoin('r.contactType', 'ct');

        $this->checkConstraintOrderBy($constraint);
        $this->checkConstraintContactType($constraint);
        $this->checkConstraintCommunity($constraint);

        return $this->qb->getQuery();
    }

    public function findList($mid)
    {
        $qb = $this->createQueryBuilder('r')
            ->select('r, ct')
            ->leftJoin('r.alumni_org_map', 'm')
            ->leftJoin('r.contactType', 'ct')
            ->where('m.id = :mid')
            ->setParameter('mid', $mid);

        $query = $qb->getQuery();
        return $query->getResult();
    }
}

