<?php

namespace Iluni\BookBundle\Repository\Detail;

use Iluni\BookBundle\Repository\CommonConstraintRepository;

/**
 * OContactsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrgContactsRepository extends CommonConstraintRepository
{
    protected static $order_by_choices = array(
        6  => 'r.id',
        23 => 'o.name',
        47 => 'ct.id'
    );

    public function findQueryFilter($constraint = array())
    {
        $this->qb = $this->createQueryBuilder('r')
            ->select('r, o, ct')
            ->leftJoin('r.organization', 'o')
            ->leftJoin('r.contactType', 'ct');

        $this->checkConstraintOrderBy($constraint);
        $this->checkConstraintContactType($constraint);

        return $this->qb->getQuery();
    }

    public function findList($oid)
    {
        $qb = $this->createQueryBuilder('r')
            ->select('r, ct')
            ->leftJoin('r.organization', 'o')
            ->leftJoin('r.contactType', 'ct')
            ->where('o.id = :oid')
            ->setParameter('oid', $oid);

        $query = $qb->getQuery();
        return $query->getResult();
    }
}

