<?php

namespace Iluni\BookBundle\Repository\Category;

use Doctrine\ORM\EntityRepository;

/**
 * CompetencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetencyRepository extends EntityRepository
{
    public function findCategories()
    {
        $qb = $this->createQueryBuilder('r')
            ->select('r, count(d) as total')
            ->leftJoin('r.acompetencies', 'd')
            ->groupBy('r.id')
            ->orderBy('r.id');

        $query = $qb->getQuery();
        $query->setHint(
            \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );
        return $query->getResult();
    }
}

