<?php

namespace Iluni\BookBundle\Repository\Category;

use Doctrine\ORM\EntityRepository;

/**
 * FacultyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacultyRepository extends EntityRepository
{
    public function findCategories()
    {
        $qb = $this->createQueryBuilder('r')
            ->select('r, d')
            ->leftJoin('r.departments', 'd')
            ->andWhere('r.id >= 0')
            ->andWhere('d.id >= 0')
            ->orderBy('r.id, d.id');

        $query = $qb->getQuery();
        $query->setHint(
            \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );
        return $query->getResult();
    }
}

