acompetencies:
    pattern:  /
    defaults: { _controller: "IluniBookBundle:Filter\ACompetencies:index" }

#acompetencies_partial_table:
#    pattern:  /
#    defaults: { _controller: "IluniBookBundle:Filter\ACompetencies:table" }
#     requirements: { _method: POST }

acompetencies_categories:
    pattern:  /categories
    defaults: { _controller: "IluniBookBundle:Filter\ACompetencies:categories" }

acompetencies_category:
    pattern:  /{cid}/cat
    defaults: { _controller: "IluniBookBundle:Filter\ACompetencies:category" }
    requirements: { cid:  \d+ }
