acompetencies:
    pattern:  /
    defaults: { _controller: "IluniBookBundle:Filter\ACompetencies:index" }

acompetencies_partial_table:
    pattern:  /table
    defaults: { _controller: "IluniBookBundle:Filter\ACompetencies:table" }

acompetencies_partial_filter:
    pattern:  /filter
    defaults: { _controller: "IluniBookBundle:Filter\ACompetencies:filter" }

acompetencies_categories:
    pattern:  /categories
    defaults: { _controller: "IluniBookBundle:Filter\ACompetencies:categories" }

acompetencies_category:
    pattern:  /{cid}/cat
    defaults: { _controller: "IluniBookBundle:Filter\ACompetencies:category" }
    requirements: { cid:  \d+ }
