acontacts:
    pattern:  /
    defaults: { _controller: "IluniBookBundle:Filter\AContacts:index" }

acontacts_partial_table:
    pattern:  /table
    defaults: { _controller: "IluniBookBundle:Filter\AContacts:table" }

acontacts_partial_filter:
    pattern:  /filter
    defaults: { _controller: "IluniBookBundle:Filter\AContacts:filter" }
