alumni:
    pattern:  /
    defaults: { _controller: "IluniBookBundle:Filter\Alumni:index" }

alumni_birthday:
    pattern:  /birthday
    defaults: { _controller: "IluniBookBundle:Filter\Birthday:index" }

alumni_birthday_month:
    pattern:  /birthday/{month}
    defaults: { _controller: "IluniBookBundle:Filter\Birthday:month" }
    requirements: { month:  \d+ }
