alumni:
    pattern:  /
    defaults: { _controller: "IluniBookBundle:Filter\Alumni:index" }

alumni_birthday:
    pattern:  /birthday
    defaults: { _controller: "IluniBookBundle:Filter\Birthday:index" }
