mcontacts:
    pattern:  /
    defaults: { _controller: "IluniBookBundle:Filter\MContacts:index" }

mcontacts_partial_table:
    pattern:  /table
    defaults: { _controller: "IluniBookBundle:Filter\MContacts:table" }

mcontacts_partial_filter:
    pattern:  /filter
    defaults: { _controller: "IluniBookBundle:Filter\MContacts:filter" }
