ocontacts:
    pattern:  /
    defaults: { _controller: "IluniBookBundle:Filter\OContacts:index" }

ocontacts_partial_table:
    pattern:  /table
    defaults: { _controller: "IluniBookBundle:Filter\OContacts:table" }

ocontacts_partial_filter:
    pattern:  /filter
    defaults: { _controller: "IluniBookBundle:Filter\OContacts:filter" }
