ofields:
    pattern:  /
    defaults: { _controller: "IluniBookBundle:Filter\OFields:index" }

ofields_categories:
    pattern:  /categories
    defaults: { _controller: "IluniBookBundle:Filter\OFields:categories" }

ofields_category:
    pattern:  /{cid}/cat
    defaults: { _controller: "IluniBookBundle:Filter\OFields:category" }
    requirements: { cid:  \d+ }

ofields_partial_table:
    pattern:  /table
    defaults: { _controller: "IluniBookBundle:Filter\OFields:table" }

ofields_partial_filter:
    pattern:  /filter
    defaults: { _controller: "IluniBookBundle:Filter\OFields:filter" }
