omap:
    pattern:  /
    defaults: { _controller: "IluniBookBundle:Filter\OMap:index" }

omap_categories:
    pattern:  /categories
    defaults: { _controller: "IluniBookBundle:Filter\OMap:categories" }

omap_category:
    pattern:  /{cid}/cat
    defaults: { _controller: "IluniBookBundle:Filter\OMap:category" }
    requirements: { cid:  \d+ }

omap_partial_table:
    pattern:  /table
    defaults: { _controller: "IluniBookBundle:Filter\OMap:table" }

omap_partial_filter:
    pattern:  /filter
    defaults: { _controller: "IluniBookBundle:Filter\OMap:filter" }
