residence:
    pattern:  /
    defaults: { _controller: "IluniBookBundle:Filter\Residence:index" }

residence_partial_table:
    pattern:  /table
    defaults: { _controller: "IluniBookBundle:Filter\Residence:table" }

residence_partial_filter:
    pattern:  /filter
    defaults: { _controller: "IluniBookBundle:Filter\Residence:filter" }
