about_alumni:
    pattern:  /{aid}/alumni/
    defaults: { _controller: "IluniBookBundle:About:alumni" }

about_org:
    pattern:  /{oid}/org/
    defaults: { _controller: "IluniBookBundle:About:org" }

about_alumni_slug:
    pattern:  /alumni/{slug}/
    defaults: { _controller: "IluniBookBundle:About:alumniSlug" }
    # requirements: { slug: .+ } # permisive slash

about_org_slug:
    pattern:  /org/{slug}/
    defaults: { _controller: "IluniBookBundle:About:orgSlug" }
    # requirements: { slug: .+ } # permisive slash

detail_alumni:
    pattern:  /{aid}/adet/
    defaults: { _controller: "IluniBookBundle:About:adet" }

detail_org:
    pattern:  /{oid}/odet/
    defaults: { _controller: "IluniBookBundle:About:odet" }

detail_alumni_org:
    pattern:  /{mid}/adeto/
    defaults: { _controller: "IluniBookBundle:About:adeto" }

detail_org_alumni:
    pattern:  /{mid}/odeta/
    defaults: { _controller: "IluniBookBundle:About:odeta" }
